export type BrandColumn = {
  range: string;
  brands: string[];
};

export const brandColumns: BrandColumn[] = [
  {
    range: 'A-C',
    brands: [
      'Acca Kappa',
      'Alessi',
      'Alessi Dolci',
      'Alkis Bat',
      'Alma K',
      'A.M. Associates',
      'A.Emery',
      'American Vintage',
      'Amina Muaddi',
      'Amouage',
      'Anna Quan',
      'Anrealage',
      'Anuschka',
      'Apiece Apart',
      'A.W.A.K.E. Mode',
      'Axel Arigato',
      'Balenciaga',
      'Birkenstock',
      'Bottega Veneta',
      'Burberry',
      'Chloé',
      'Coach',
    ],
  },
  {
    range: 'D-H',
    brands: [
      'D1 Milano',
      "D'accori",
      'Daily Paper',
      'Damiani',
      'DANNIJO',
      'Deus Ex Machina',
      'Devialet',
      'Diadora Heritage',
      'Diesel',
      'Diptyque',
      'Dolce & Gabbana',
      'Dondup',
      'Dr. Martens',
      'Dsquared2',
      'Duvetica',
      'EA7',
      'Eastpak',
      'Eden Park',
      'Fendi',
      'Filson',
      'Ganni',
      'Gucci',
      'Hermès',
    ],
  },
  {
    range: 'I-L',
    brands: [
      'Iceberg',
      'Il Gufo',
      'Incotex',
      'Isabel Marant',
      'J.Lindeberg',
      'Jacquemus',
      'Jil Sander',
      'Kenzo',
      'Khaite',
      'Kiton',
      'Lacoste',
      'Lanvin',
      'Lemaire',
      'Loewe',
      'Longchamp',
      'Loro Piana',
      'Louis Vuitton',
    ],
  },
  {
    range: 'M-P',
    brands: [
      'Maison Margiela',
      'Marni',
      'Max Mara',
      'Missoni',
      'Moncler',
      'Moschino',
      'Off-White',
      'Pal Zileri',
      'Patagonia',
      'Persol',
      'Philosophy',
      'Pinko',
      'Prada',
      'Premiata',
      'Psycho Bunny',
      'Puma',
    ],
  },
  {
    range: 'R-Z',
    brands: [
      'Ray-Ban',
      'Re/Done',
      'Red Wing',
      'Represent',
      'Rhude',
      'Rick Owens',
      'Salomon',
      'Santoni',
      'Stone Island',
      'Sunnei',
      'The North Face',
      'Thom Browne',
      'Timberland',
      'Tom Ford',
      'Valentino',
      'Versace',
      'Y-3',
      'Zegna',
    ],
  },
];
